-- Wipe and replace pricing data
DELETE FROM public.zip_pricing;
DELETE FROM public.catalog_items;

INSERT INTO public.zip_pricing (zip_code, minimum_price, active) VALUES
  ('98155', 150.0, true), ('98028', 150.0, true), ('98133', 150.0, true), ('98043', 150.0, true), ('98125', 150.0, true), ('98036', 150.0, true), ('98177', 150.0, true), ('98011', 150.0, true), ('98034', 150.0, true),
  ('98115', 175.0, true), ('98021', 175.0, true), ('98020', 175.0, true), ('98026', 175.0, true), ('98037', 175.0, true), ('98131', 175.0, true), ('98117', 175.0, true), ('98103', 175.0, true), ('98105', 175.0, true), ('98033', 175.0, true), ('98107', 175.0, true), ('98012', 175.0, true), ('98072', 175.0, true), ('98087', 175.0, true), ('98102', 175.0, true), ('98112', 175.0, true), ('98109', 175.0, true), ('98119', 175.0, true), ('98199', 175.0, true), ('98039', 175.0, true), ('98052', 175.0, true), ('98122', 175.0, true),
  ('98204', 200.0, true), ('98121', 200.0, true), ('98101', 200.0, true), ('98004', 200.0, true), ('98164', 200.0, true), ('98154', 200.0, true), ('98174', 200.0, true), ('98104', 200.0, true), ('98161', 200.0, true), ('98342', 200.0, true), ('98275', 200.0, true), ('98005', 200.0, true), ('98077', 200.0, true), ('98208', 200.0, true), ('98296', 200.0, true), ('98346', 200.0, true), ('98007', 200.0, true), ('98144', 200.0, true), ('98392', 200.0, true), ('98134', 200.0, true), ('98116', 200.0, true), ('98203', 200.0, true), ('98110', 200.0, true), ('98040', 200.0, true), ('98008', 200.0, true), ('98053', 200.0, true), ('98126', 200.0, true), ('98106', 200.0, true), ('98074', 200.0, true), ('98118', 200.0, true), ('98108', 200.0, true), ('98236', 200.0, true),
  ('98370', 225.0, true), ('98006', 225.0, true), ('98136', 225.0, true), ('98340', 225.0, true), ('98075', 225.0, true), ('98201', 225.0, true), ('98056', 225.0, true), ('98146', 225.0, true), ('98178', 225.0, true), ('98311', 225.0, true), ('98168', 225.0, true), ('98290', 225.0, true), ('98029', 225.0, true), ('98310', 225.0, true), ('98059', 225.0, true), ('98366', 225.0, true), ('98315', 225.0, true), ('98014', 225.0, true), ('98057', 225.0, true),
  ('98383', 250.0, true), ('98337', 250.0, true), ('98260', 250.0, true), ('98272', 250.0, true), ('98158', 250.0, true), ('98188', 250.0, true), ('98365', 250.0, true), ('98148', 250.0, true), ('98166', 250.0, true), ('98055', 250.0, true), ('98270', 250.0, true), ('98249', 250.0, true), ('98027', 250.0, true), ('98258', 250.0, true), ('98019', 250.0, true), ('98271', 250.0, true), ('98058', 250.0, true), ('98031', 250.0, true), ('98070', 250.0, true), ('98312', 250.0, true);

INSERT INTO public.catalog_items (id, name, category, price, sort_order, active) VALUES
  ('bed-frame-bed-frame-full-queen', 'Bed Frame - Full/Queen', 'Bed Frame', 57.0, 0, true),
  ('bed-frame-bed-base-foundation-full', 'Bed Base/Foundation - Full', 'Bed Frame', 57.0, 1, true),
  ('bed-frame-bed-base-foundation-king-cal-king', 'Bed Base/Foundation - King/Cal King', 'Bed Frame', 86.0, 2, true),
  ('bed-frame-bed-base-foundation-queen', 'Bed Base/Foundation - Queen', 'Bed Frame', 67.0, 3, true),
  ('bed-frame-bed-base-foundation-twin', 'Bed Base/Foundation - Twin', 'Bed Frame', 48.0, 4, true),
  ('bed-frame-bed-foundation', 'Bed Foundation', 'Bed Frame', 57.0, 5, true),
  ('bed-frame-bed-frame', 'Bed Frame', 'Bed Frame', 57.0, 6, true),
  ('bed-frame-bed-frame-king-cal-king', 'Bed Frame - King/Cal King', 'Bed Frame', 76.0, 7, true),
  ('bed-frame-bed-frame-twin', 'Bed Frame - Twin', 'Bed Frame', 48.0, 8, true),
  ('bed-frame-bed-side-rails', 'Bed Side Rails', 'Bed Frame', 38.0, 9, true),
  ('bed-frame-bedframe-with-drawers', 'Bedframe with Drawers', 'Bed Frame', 95.0, 10, true),
  ('bed-frame-bunkbed', 'Bunkbed', 'Bed Frame', 238.0, 11, true),
  ('bed-frame-bunky-boards', 'Bunky Boards', 'Bed Frame', 29.0, 12, true),
  ('bed-frame-cot', 'Cot', 'Bed Frame', 38.0, 13, true),
  ('bed-frame-daybed', 'Daybed', 'Bed Frame', 105.0, 14, true),
  ('bed-frame-footboard', 'Footboard', 'Bed Frame', 29.0, 15, true),
  ('bed-frame-headboard', 'Headboard', 'Bed Frame', 29.0, 16, true),
  ('bed-frame-murphy-bed', 'Murphy Bed', 'Bed Frame', 143.0, 17, true),
  ('bed-frame-waterbed', 'Waterbed', 'Bed Frame', 570.0, 18, true),
  ('box-spring-adjustable-bed-base-full', 'Adjustable Bed Base - Full', 'Box Spring', 67.0, 19, true),
  ('box-spring-adjustable-bed-base-king-cal-king', 'Adjustable Bed Base - King/Cal King', 'Box Spring', 86.0, 20, true),
  ('box-spring-adjustable-bed-base-queen', 'Adjustable Bed Base - Queen', 'Box Spring', 76.0, 21, true),
  ('box-spring-adjustable-bed-base-twin', 'Adjustable Bed Base - Twin', 'Box Spring', 67.0, 22, true),
  ('box-spring-box-spring', 'Box Spring', 'Box Spring', 29.0, 23, true),
  ('box-spring-box-spring-full', 'Box Spring - Full', 'Box Spring', 38.0, 24, true),
  ('box-spring-box-spring-king-cal-king', 'Box Spring - King/Cal King', 'Box Spring', 57.0, 25, true),
  ('box-spring-box-spring-queen', 'Box Spring - Queen', 'Box Spring', 38.0, 26, true),
  ('box-spring-box-spring-twin', 'Box Spring - Twin', 'Box Spring', 29.0, 27, true),
  ('cabinet-cabinet', 'Cabinet', 'Cabinet', 57.0, 28, true),
  ('cabinet-cabinet-large', 'Cabinet - Large', 'Cabinet', 76.0, 29, true),
  ('cabinet-china-cabinet', 'China Cabinet', 'Cabinet', 143.0, 30, true),
  ('cabinet-dining-china-hutch', 'Dining / China Hutch', 'Cabinet', 285.0, 31, true),
  ('cabinet-small-cabinet', 'Small Cabinet', 'Cabinet', 57.0, 32, true),
  ('boxes', 'Bundle of 10 broken down Moving Boxes', 'Cardboard Box', 48.0, 33, true),
  ('cardboard-box-cardboard-large-bale', 'Cardboard - Large Bale', 'Cardboard Box', 238.0, 34, true),
  ('cardboard-box-cardboard-medium-bale', 'Cardboard - Medium Bale', 'Cardboard Box', 143.0, 35, true),
  ('cardboard-box-cardboard-small-bale', 'Cardboard - Small Bale', 'Cardboard Box', 76.0, 36, true),
  ('cardboard-box-cardboard-box-not-broken-down', 'Cardboard Box (Not Broken Down)', 'Cardboard Box', 13.0, 37, true),
  ('carpet-area-rug-6x9-or-smaller', 'Area Rug (6x9 or smaller)', 'Carpet', 48.0, 38, true),
  ('carpet-area-rug-larger-than-6x9', 'Area Rug (larger than 6x9)', 'Carpet', 76.0, 39, true),
  ('carpet-carpet', 'Carpet', 'Carpet', 48.0, 40, true),
  ('chair', 'Chair', 'Chair', 38.0, 41, true),
  ('chair-club-chair', 'Club Chair', 'Chair', 57.0, 42, true),
  ('chair-folding-event-chairs', 'Folding Event Chairs', 'Chair', 19.0, 43, true),
  ('chair-glider-rocking-chair', 'Glider - Rocking Chair', 'Chair', 57.0, 44, true),
  ('chair-glider-with-ottoman-rocking-chair', 'Glider with Ottoman - Rocking Chair', 'Chair', 95.0, 45, true),
  ('chair-massage-chair', 'Massage Chair', 'Chair', 190.0, 46, true),
  ('chair-office-chair', 'Office Chair', 'Chair', 48.0, 47, true),
  ('chair-rocking-chair', 'Rocking chair', 'Chair', 57.0, 48, true),
  ('chair-salon-chair', 'Salon Chair', 'Chair', 76.0, 49, true),
  ('couch', 'Couch / Loveseat', 'Couch', 57.0, 50, true),
  ('couch-futon', 'Futon', 'Couch', 95.0, 51, true),
  ('loveseat', 'Loveseat - Reclining', 'Couch', 143.0, 52, true),
  ('couch-reclining-sofa', 'Reclining Sofa', 'Couch', 181.0, 53, true),
  ('couch-sectional-with-built-in-recliner', 'Sectional - with built in Recliner', 'Couch', 428.0, 54, true),
  ('couch-sectional-with-built-in-sleeper', 'Sectional - with built in Sleeper', 'Couch', 475.0, 55, true),
  ('couch-sectional-sofa-2-pieces', 'Sectional Sofa - 2 pieces', 'Couch', 95.0, 56, true),
  ('couch-sectional-sofa-3-pieces', 'Sectional Sofa - 3 pieces', 'Couch', 143.0, 57, true),
  ('couch-sectional-sofa-4-pieces', 'Sectional Sofa - 4 pieces', 'Couch', 238.0, 58, true),
  ('couch-sectional-sofa-5-pieces', 'Sectional Sofa - 5 pieces', 'Couch', 285.0, 59, true),
  ('couch-sectional-sofa-6-pieces', 'Sectional Sofa - 6+ pieces', 'Couch', 380.0, 60, true),
  ('couch-sleeper-sofa', 'Sleeper Sofa', 'Couch', 133.0, 61, true),
  ('desk-cubicle', 'Cubicle', 'Desk', 171.0, 62, true),
  ('desk', 'Desk', 'Desk', 57.0, 63, true),
  ('desk-desk-executive', 'Desk - Executive', 'Desk', 152.0, 64, true),
  ('desk-desk-l-shaped', 'Desk - L-Shaped', 'Desk', 76.0, 65, true),
  ('desk-desk-motorized-sit-stand', 'Desk - Motorized Sit/Stand', 'Desk', 95.0, 66, true),
  ('desk-desk-u-shaped', 'Desk - U Shaped', 'Desk', 67.0, 67, true),
  ('desk-hutch', 'Hutch', 'Desk', 67.0, 68, true),
  ('desk-podium', 'Podium', 'Desk', 38.0, 69, true),
  ('dresser', 'Combo Dresser', 'Dresser', 114.0, 70, true),
  ('dresser-double-dresser', 'Double Dresser', 'Dresser', 105.0, 71, true),
  ('dresser-dresser', 'Dresser', 'Dresser', 57.0, 72, true),
  ('dresser-gentleman-s-chest', 'Gentleman''s Chest', 'Dresser', 95.0, 73, true),
  ('dresser-horizontal-chest-of-drawers', 'Horizontal Chest of Drawers', 'Dresser', 95.0, 74, true),
  ('dresser-horizontal-dresser', 'Horizontal Dresser', 'Dresser', 95.0, 75, true),
  ('dresser-lingerie-chest', 'Lingerie Chest', 'Dresser', 67.0, 76, true),
  ('dresser-mirror-dresser', 'Mirror - Dresser', 'Dresser', 57.0, 77, true),
  ('dresser-nightstand', 'Nightstand', 'Dresser', 38.0, 78, true),
  ('dresser-vertical-chest-of-drawers', 'Vertical Chest of Drawers', 'Dresser', 76.0, 79, true),
  ('dresser-vertical-dresser', 'Vertical Dresser', 'Dresser', 76.0, 80, true),
  ('freezer-freezer', 'Freezer', 'Freezer', 105.0, 81, true),
  ('freezer-freezer-commercial-size', 'Freezer - Commercial Size', 'Freezer', 855.0, 82, true),
  ('freezer-freezer-residential-upright', 'Freezer - Residential Upright', 'Freezer', 105.0, 83, true),
  ('freezer-freezer-chest', 'Freezer Chest', 'Freezer', 95.0, 84, true),
  ('freezer-ice-machine', 'Ice Machine', 'Freezer', 190.0, 85, true),
  ('freezer-ice-maker', 'Ice Maker', 'Freezer', 38.0, 86, true),
  ('freezer-wine-cooler-large', 'Wine Cooler - Large', 'Freezer', 285.0, 87, true),
  ('freezer-wine-cooler-small', 'Wine Cooler - Small', 'Freezer', 95.0, 88, true),
  ('grill', 'Grill', 'Grill', 67.0, 89, true),
  ('grill-grill-propane', 'Grill - Propane', 'Grill', 95.0, 90, true),
  ('grill-propane-tank-120-gallon', 'Propane Tank - 120 Gallon', 'Grill', 380.0, 91, true),
  ('grill-propane-tank-20lb-grill-size', 'Propane Tank - 20lb Grill Size', 'Grill', 38.0, 92, true),
  ('grill-propane-tank-250-gallon-tank', 'Propane tank - 250+ Gallon Tank', 'Grill', 1900.0, 93, true),
  ('grill-smoker', 'Smoker', 'Grill', 95.0, 94, true),
  ('mattress', 'Mattress', 'Mattress', 57.0, 95, true),
  ('mattress-mattress-crib', 'Mattress - Crib', 'Mattress', 29.0, 96, true),
  ('mattress-mattress-full', 'Mattress - Full', 'Mattress', 57.0, 97, true),
  ('mattress-mattress-king-cal-king', 'Mattress - King/Cal King', 'Mattress', 76.0, 98, true),
  ('mattress-mattress-queen', 'Mattress - Queen', 'Mattress', 67.0, 99, true),
  ('mattress-mattress-twin', 'Mattress - Twin', 'Mattress', 48.0, 100, true),
  ('mattress-mattress-topper', 'Mattress Topper', 'Mattress', 38.0, 101, true),
  ('range-cooktop', 'Cooktop', 'Range', 48.0, 102, true),
  ('range-hood', 'Hood', 'Range', 38.0, 103, true),
  ('oven', 'Oven - Double Wall Oven', 'Range', 152.0, 104, true),
  ('range-oven-kitchen', 'Oven - Kitchen', 'Range', 76.0, 105, true),
  ('range-range', 'Range', 'Range', 76.0, 106, true),
  ('range-range-commercial-size', 'Range - Commercial Size', 'Range', 228.0, 107, true),
  ('range-range-oven', 'Range / Oven', 'Range', 76.0, 108, true),
  ('range-stove', 'Stove', 'Range', 76.0, 109, true),
  ('refrigerator-cvm-11', 'CVM-11', 'Refrigerator', 333.0, 110, true),
  ('refrigerator-cvm-13', 'CVM-13', 'Refrigerator', 333.0, 111, true),
  ('refrigerator-cvm-27', 'CVM-27', 'Refrigerator', 428.0, 112, true),
  ('refrigerator-evc04', 'EVC04', 'Refrigerator', 190.0, 113, true),
  ('refrigerator-gdm-10', 'GDM-10', 'Refrigerator', 333.0, 114, true),
  ('refrigerator-gdm-12', 'GDM-12', 'Refrigerator', 285.0, 115, true),
  ('refrigerator-gdm-15', 'GDM-15', 'Refrigerator', 333.0, 116, true),
  ('refrigerator-gdm-23', 'GDM-23', 'Refrigerator', 428.0, 117, true),
  ('refrigerator-gdm-33', 'GDM-33', 'Refrigerator', 475.0, 118, true),
  ('refrigerator-gdm-33-mini', 'GDM-33 Mini', 'Refrigerator', 475.0, 119, true),
  ('fridge', 'Refrigerator', 'Refrigerator', 114.0, 120, true),
  ('refrigerator-refrigerator-commercial-size', 'Refrigerator - Commercial Size', 'Refrigerator', 855.0, 121, true),
  ('refrigerator-refrigerator-mini', 'Refrigerator - Mini', 'Refrigerator', 57.0, 122, true),
  ('refrigerator-refrigerator-residential-built-in', 'Refrigerator - Residential built-In', 'Refrigerator', 523.0, 123, true),
  ('refrigerator-refrigerator-residential-standard', 'Refrigerator - Residential Standard', 'Refrigerator', 114.0, 124, true),
  ('refrigerator-vending-machine', 'Vending Machine', 'Refrigerator', 523.0, 125, true),
  ('refrigerator-vro8', 'VRO8', 'Refrigerator', 285.0, 126, true),
  ('table-marble-concrete-table', 'Marble/Concrete Table', 'Table', 171.0, 127, true),
  ('table-sideboard', 'Sideboard', 'Table', 67.0, 128, true),
  ('table-table', 'Table', 'Table', 76.0, 129, true),
  ('table-table-coffee', 'Table - Coffee', 'Table', 48.0, 130, true),
  ('table-table-conference-room-table', 'Table - Conference Room Table', 'Table', 143.0, 131, true),
  ('table-table-dining', 'Table - Dining', 'Table', 76.0, 132, true),
  ('tv', 'Television', 'Television', 95.0, 133, true),
  ('television-television-flat-screen-25in-or-less', 'Television - Flat Screen - 25in or less', 'Television', 48.0, 134, true),
  ('television-television-flat-screen-26in-to-42in', 'Television - Flat Screen - 26in to 42in', 'Television', 67.0, 135, true),
  ('television-television-flat-screen-42in-or-larger', 'Television - Flat Screen - 42in or larger', 'Television', 95.0, 136, true),
  ('television-television-projection', 'Television - Projection', 'Television', 285.0, 137, true),
  ('television-television-tube-25in-or-larger', 'Television - Tube 25in or larger', 'Television', 523.0, 138, true),
  ('television-television-tube-25in-or-under', 'Television - Tube 25in or under', 'Television', 238.0, 139, true),
  ('treadmill-treadmill-commercial', 'Treadmill - Commercial', 'Treadmill', 380.0, 140, true),
  ('treadmill-treadmill-residential', 'Treadmill - Residential', 'Treadmill', 181.0, 141, true),
  ('tv-stand-entertainment-center-3-piece', 'Entertainment Center - 3 piece', 'TV Stand', 380.0, 142, true),
  ('tv-stand-entertainment-center-large', 'Entertainment Center - Large', 'TV Stand', 143.0, 143, true),
  ('tv-stand-entertainment-center-small', 'Entertainment Center - Small', 'TV Stand', 57.0, 144, true),
  ('tv-stand-tv-stand', 'TV Stand', 'TV Stand', 57.0, 145, true),
  ('miscellaneous-unknown-proof-of-disposal', 'Proof of Disposal', 'Miscellaneous / Unknown', 48.0, 146, true),
  ('miscellaneous-unknown-1-car-garage-cleanout', '1 Car Garage Cleanout', 'Miscellaneous / Unknown', 950.0, 147, true),
  ('miscellaneous-unknown-1-3-cubic-yard-of-loose-items', '1/3 Cubic Yard of Loose Items', 'Miscellaneous / Unknown', 86.0, 148, true),
  ('miscellaneous-unknown-16oz-propane-canister', '16oz Propane Canister', 'Miscellaneous / Unknown', 10.0, 149, true),
  ('miscellaneous-unknown-2-car-garage-cleanout', '2 Car Garage Cleanout', 'Miscellaneous / Unknown', 1520.0, 150, true),
  ('miscellaneous-unknown-3-car-garage-cleanout', '3 Car Garage Cleanout', 'Miscellaneous / Unknown', 2090.0, 151, true),
  ('miscellaneous-unknown-30-range', '30" Range', 'Miscellaneous / Unknown', 76.0, 152, true),
  ('miscellaneous-unknown-36-range', '36" Range', 'Miscellaneous / Unknown', 95.0, 153, true),
  ('miscellaneous-unknown-48-range', '48" Range', 'Miscellaneous / Unknown', 190.0, 154, true),
  ('miscellaneous-unknown-55-gallon-plastic-drum', '55 Gallon Plastic Drum', 'Miscellaneous / Unknown', 475.0, 155, true),
  ('miscellaneous-unknown-60-range', '60" Range', 'Miscellaneous / Unknown', 285.0, 156, true),
  ('miscellaneous-unknown-above-ground-pool', 'Above Ground Pool', 'Miscellaneous / Unknown', 1520.0, 157, true),
  ('miscellaneous-unknown-adjustable-bed-base', 'Adjustable Bed Base', 'Miscellaneous / Unknown', 67.0, 158, true),
  ('miscellaneous-unknown-air-conditioner', 'Air Conditioner', 'Miscellaneous / Unknown', 190.0, 159, true),
  ('miscellaneous-unknown-air-conditioner-window-unit', 'Air Conditioner - Window Unit', 'Miscellaneous / Unknown', 48.0, 160, true),
  ('miscellaneous-unknown-aquarium-large', 'Aquarium - large', 'Miscellaneous / Unknown', 238.0, 161, true),
  ('miscellaneous-unknown-aquarium-medium', 'Aquarium - Medium', 'Miscellaneous / Unknown', 143.0, 162, true),
  ('miscellaneous-unknown-aquarium-small', 'Aquarium - small', 'Miscellaneous / Unknown', 57.0, 163, true),
  ('miscellaneous-unknown-artificial-christmas-tree-10ft-or-less', 'Artificial Christmas Tree (10ft or less)', 'Miscellaneous / Unknown', 57.0, 164, true),
  ('miscellaneous-unknown-atv', 'ATV', 'Miscellaneous / Unknown', 570.0, 165, true),
  ('miscellaneous-unknown-automotive-rim', 'Automotive Rim', 'Miscellaneous / Unknown', 95.0, 166, true),
  ('tires', 'Automotive Rim and Tire', 'Miscellaneous / Unknown', 133.0, 167, true),
  ('miscellaneous-unknown-baby-car-seat', 'Baby Car Seat', 'Miscellaneous / Unknown', 29.0, 168, true),
  ('miscellaneous-unknown-baby-changing-table', 'Baby Changing Table', 'Miscellaneous / Unknown', 38.0, 169, true),
  ('miscellaneous-unknown-baby-swing', 'Baby Swing', 'Miscellaneous / Unknown', 38.0, 170, true),
  ('miscellaneous-unknown-baby-walker', 'Baby Walker', 'Miscellaneous / Unknown', 29.0, 171, true),
  ('miscellaneous-unknown-bag-of-junk', 'Bag of Junk', 'Miscellaneous / Unknown', 48.0, 172, true),
  ('miscellaneous-unknown-basement-cleanout', 'Basement Cleanout', 'Miscellaneous / Unknown', 2090.0, 173, true),
  ('miscellaneous-unknown-basi-systems-reformer', 'Basi Systems Reformer', 'Miscellaneous / Unknown', 285.0, 174, true),
  ('miscellaneous-unknown-basketball-goal', 'Basketball Goal', 'Miscellaneous / Unknown', 76.0, 175, true),
  ('miscellaneous-unknown-bathroom-cleanout', 'Bathroom Cleanout', 'Miscellaneous / Unknown', 285.0, 176, true),
  ('miscellaneous-unknown-bathtub-cast-iron', 'Bathtub - Cast Iron', 'Miscellaneous / Unknown', 570.0, 177, true),
  ('miscellaneous-unknown-bathtub-fiberglass', 'Bathtub - Fiberglass', 'Miscellaneous / Unknown', 190.0, 178, true),
  ('miscellaneous-unknown-bathtub-porcelain', 'Bathtub - Porcelain', 'Miscellaneous / Unknown', 380.0, 179, true),
  ('miscellaneous-unknown-beanbag-large', 'Beanbag - Large', 'Miscellaneous / Unknown', 57.0, 180, true),
  ('miscellaneous-unknown-beanbag-standard-size', 'Beanbag - Standard size', 'Miscellaneous / Unknown', 29.0, 181, true),
  ('miscellaneous-unknown-bedroom-cleanout-large', 'Bedroom Cleanout - Large', 'Miscellaneous / Unknown', 760.0, 182, true),
  ('miscellaneous-unknown-bedroom-cleanout-small', 'Bedroom Cleanout - Small', 'Miscellaneous / Unknown', 475.0, 183, true),
  ('miscellaneous-unknown-bench', 'Bench', 'Miscellaneous / Unknown', 48.0, 184, true),
  ('miscellaneous-unknown-bicycle', 'Bicycle', 'Miscellaneous / Unknown', 38.0, 185, true),
  ('miscellaneous-unknown-books-cd-dvd', 'Books, CD, DVD', 'Miscellaneous / Unknown', 29.0, 186, true),
  ('bookshelf', 'Bookshelf', 'Miscellaneous / Unknown', 57.0, 187, true),
  ('miscellaneous-unknown-box-of-junk', 'Box of Junk', 'Miscellaneous / Unknown', 48.0, 188, true),
  ('miscellaneous-unknown-box-of-tile', 'Box of Tile', 'Miscellaneous / Unknown', 48.0, 189, true),
  ('miscellaneous-unknown-brush-pile-large', 'Brush Pile - Large', 'Miscellaneous / Unknown', 1235.0, 190, true),
  ('miscellaneous-unknown-brush-pile-small', 'Brush Pile - Small', 'Miscellaneous / Unknown', 475.0, 191, true),
  ('miscellaneous-unknown-carpet-steamer', 'Carpet Steamer', 'Miscellaneous / Unknown', 38.0, 192, true),
  ('miscellaneous-unknown-casket', 'Casket', 'Miscellaneous / Unknown', 333.0, 193, true),
  ('miscellaneous-unknown-cat-tree', 'Cat Tree', 'Miscellaneous / Unknown', 57.0, 194, true),
  ('miscellaneous-unknown-ceiling-fan', 'Ceiling Fan', 'Miscellaneous / Unknown', 38.0, 195, true),
  ('miscellaneous-unknown-chaise-lounge', 'Chaise Lounge', 'Miscellaneous / Unknown', 67.0, 196, true),
  ('miscellaneous-unknown-chandelier-large', 'Chandelier - Large', 'Miscellaneous / Unknown', 95.0, 197, true),
  ('miscellaneous-unknown-chandelier-small', 'Chandelier - Small', 'Miscellaneous / Unknown', 57.0, 198, true),
  ('miscellaneous-unknown-chest', 'Chest', 'Miscellaneous / Unknown', 38.0, 199, true),
  ('miscellaneous-unknown-christmas-tree-live-10ft-or-less', 'Christmas Tree (Live) (10ft or less)', 'Miscellaneous / Unknown', 57.0, 200, true),
  ('miscellaneous-unknown-clock-grandfather', 'Clock - Grandfather', 'Miscellaneous / Unknown', 67.0, 201, true),
  ('miscellaneous-unknown-commercial-tire-automotive', 'Commercial Tire - Automotive', 'Miscellaneous / Unknown', 124.0, 202, true),
  ('miscellaneous-unknown-cooler', 'Cooler', 'Miscellaneous / Unknown', 29.0, 203, true),
  ('miscellaneous-unknown-countertop-laminates', 'Countertop - Laminates', 'Miscellaneous / Unknown', 57.0, 204, true),
  ('miscellaneous-unknown-countertop-stone', 'Countertop - Stone', 'Miscellaneous / Unknown', 95.0, 205, true),
  ('miscellaneous-unknown-crib', 'Crib', 'Miscellaneous / Unknown', 57.0, 206, true),
  ('miscellaneous-unknown-custom-job-l', 'Custom Job - L', 'Miscellaneous / Unknown', 1900.0, 207, true),
  ('miscellaneous-unknown-custom-job-m', 'Custom Job - M', 'Miscellaneous / Unknown', 475.0, 208, true),
  ('miscellaneous-unknown-custom-job-s', 'Custom Job - S', 'Miscellaneous / Unknown', 95.0, 209, true),
  ('miscellaneous-unknown-custom-job-xs', 'Custom Job - XS', 'Miscellaneous / Unknown', 38.0, 210, true),
  ('miscellaneous-unknown-den-cleanout', 'Den Cleanout', 'Miscellaneous / Unknown', 950.0, 211, true),
  ('washer', 'Dishwasher', 'Miscellaneous / Unknown', 76.0, 212, true),
  ('miscellaneous-unknown-e-bike', 'E-Bike', 'Miscellaneous / Unknown', 95.0, 213, true),
  ('miscellaneous-unknown-electric-fireplace', 'Electric Fireplace', 'Miscellaneous / Unknown', 143.0, 214, true),
  ('miscellaneous-unknown-electric-heater-large', 'Electric Heater - Large', 'Miscellaneous / Unknown', 143.0, 215, true),
  ('miscellaneous-unknown-electric-heater-small', 'Electric Heater - Small', 'Miscellaneous / Unknown', 48.0, 216, true),
  ('miscellaneous-unknown-electric-scooter', 'Electric Scooter', 'Miscellaneous / Unknown', 143.0, 217, true),
  ('miscellaneous-unknown-elliptical', 'Elliptical', 'Miscellaneous / Unknown', 181.0, 218, true),
  ('miscellaneous-unknown-end-table', 'End table', 'Miscellaneous / Unknown', 38.0, 219, true),
  ('miscellaneous-unknown-exercise-bike', 'Exercise Bike', 'Miscellaneous / Unknown', 95.0, 220, true),
  ('miscellaneous-unknown-exterior-door', 'Exterior Door', 'Miscellaneous / Unknown', 143.0, 221, true),
  ('miscellaneous-unknown-ezgrubbench', 'EZGrubBench', 'Miscellaneous / Unknown', 95.0, 222, true),
  ('miscellaneous-unknown-ezgrubtub', 'EZGrubTub', 'Miscellaneous / Unknown', 95.0, 223, true),
  ('miscellaneous-unknown-family-room-cleanout', 'Family Room Cleanout', 'Miscellaneous / Unknown', 950.0, 224, true),
  ('miscellaneous-unknown-file-cabinet-2-or-3-drawer', 'File Cabinet - 2 or 3 drawer', 'Miscellaneous / Unknown', 76.0, 225, true),
  ('miscellaneous-unknown-file-cabinet-4-or-5-drawer', 'File Cabinet - 4 or 5 drawer', 'Miscellaneous / Unknown', 143.0, 226, true),
  ('miscellaneous-unknown-filing-cabinet', 'Filing Cabinet', 'Miscellaneous / Unknown', 48.0, 227, true),
  ('miscellaneous-unknown-floor-jack', 'Floor Jack', 'Miscellaneous / Unknown', 38.0, 228, true),
  ('miscellaneous-unknown-foosball-or-residential-game-room-table-games', 'Foosball or Residential Game Room Table Games', 'Miscellaneous / Unknown', 285.0, 229, true),
  ('miscellaneous-unknown-generator-portable', 'Generator - Portable', 'Miscellaneous / Unknown', 143.0, 230, true),
  ('miscellaneous-unknown-generator-stationary', 'Generator - Stationary', 'Miscellaneous / Unknown', 475.0, 231, true),
  ('miscellaneous-unknown-golf-clubs', 'Golf Clubs', 'Miscellaneous / Unknown', 38.0, 232, true),
  ('miscellaneous-unknown-highchair', 'Highchair', 'Miscellaneous / Unknown', 38.0, 233, true),
  ('miscellaneous-unknown-home-gym', 'Home Gym', 'Miscellaneous / Unknown', 380.0, 234, true),
  ('miscellaneous-unknown-hospital-bed', 'Hospital Bed', 'Miscellaneous / Unknown', 855.0, 235, true),
  ('hot-tub', 'Hot tub', 'Miscellaneous / Unknown', 1558.0, 236, true),
  ('miscellaneous-unknown-hot-tub-cover', 'Hot Tub Cover', 'Miscellaneous / Unknown', 57.0, 237, true),
  ('miscellaneous-unknown-interior-door', 'Interior Door', 'Miscellaneous / Unknown', 57.0, 238, true),
  ('miscellaneous-unknown-ironing-board', 'Ironing Board', 'Miscellaneous / Unknown', 29.0, 239, true),
  ('miscellaneous-unknown-jackhammer', 'Jackhammer', 'Miscellaneous / Unknown', 190.0, 240, true),
  ('miscellaneous-unknown-junk-pile-large', 'Junk Pile - Large', 'Miscellaneous / Unknown', 1140.0, 241, true),
  ('miscellaneous-unknown-junk-pile-small', 'Junk Pile - Small', 'Miscellaneous / Unknown', 665.0, 242, true),
  ('miscellaneous-unknown-keyboard-electric', 'Keyboard - Electric', 'Miscellaneous / Unknown', 95.0, 243, true),
  ('miscellaneous-unknown-kids-bike', 'Kids Bike', 'Miscellaneous / Unknown', 38.0, 244, true),
  ('miscellaneous-unknown-kitchen-cleanout', 'Kitchen Cleanout', 'Miscellaneous / Unknown', 665.0, 245, true),
  ('miscellaneous-unknown-ladder', 'Ladder', 'Miscellaneous / Unknown', 48.0, 246, true),
  ('miscellaneous-unknown-lamp', 'Lamp', 'Miscellaneous / Unknown', 29.0, 247, true),
  ('miscellaneous-unknown-large-sports-equipment', 'Large Sports Equipment', 'Miscellaneous / Unknown', 57.0, 248, true),
  ('miscellaneous-unknown-large-wall-decor', 'Large Wall Decor', 'Miscellaneous / Unknown', 48.0, 249, true),
  ('miscellaneous-unknown-lawnmower-push', 'Lawnmower - Push', 'Miscellaneous / Unknown', 95.0, 250, true),
  ('miscellaneous-unknown-lawnmower-riding', 'Lawnmower - Riding', 'Miscellaneous / Unknown', 570.0, 251, true),
  ('miscellaneous-unknown-leafblower', 'Leafblower', 'Miscellaneous / Unknown', 95.0, 252, true),
  ('miscellaneous-unknown-linens', 'Linens', 'Miscellaneous / Unknown', 10.0, 253, true),
  ('miscellaneous-unknown-living-room-cleanout', 'Living Room Cleanout', 'Miscellaneous / Unknown', 950.0, 254, true),
  ('miscellaneous-unknown-luggage', 'Luggage', 'Miscellaneous / Unknown', 38.0, 255, true),
  ('miscellaneous-unknown-mattress-coil-set', 'Mattress Coil Set', 'Miscellaneous / Unknown', 76.0, 256, true),
  ('miscellaneous-unknown-medical-treatment-table', 'Medical Treatment Table', 'Miscellaneous / Unknown', 143.0, 257, true),
  ('microwave', 'Microwave', 'Miscellaneous / Unknown', 29.0, 258, true),
  ('miscellaneous-unknown-mileage', 'Mileage', 'Miscellaneous / Unknown', 6.0, 259, true),
  ('miscellaneous-unknown-mirror', 'Mirror', 'Miscellaneous / Unknown', 57.0, 260, true),
  ('miscellaneous-unknown-misc-large-unlisted-item', 'Misc. Large Unlisted Item', 'Miscellaneous / Unknown', 285.0, 261, true),
  ('miscellaneous-unknown-misc-medium-unlisted-item', 'Misc. Medium Unlisted Item', 'Miscellaneous / Unknown', 143.0, 262, true),
  ('miscellaneous-unknown-misc-small-unlisted-item', 'Misc. Small Unlisted Item', 'Miscellaneous / Unknown', 67.0, 263, true),
  ('misc', 'Miscellaneous Garden Equipment - Small', 'Miscellaneous / Unknown', 19.0, 264, true),
  ('miscellaneous-unknown-miscellaneous-home-decor', 'Miscellaneous Home Decor', 'Miscellaneous / Unknown', 29.0, 265, true),
  ('miscellaneous-unknown-miscellaneous-power-tools', 'Miscellaneous Power Tools', 'Miscellaneous / Unknown', 29.0, 266, true),
  ('miscellaneous-unknown-miscellaneous-small-electronics', 'Miscellaneous Small Electronics', 'Miscellaneous / Unknown', 29.0, 267, true),
  ('miscellaneous-unknown-miscellaneous-small-exercise-equipment', 'Miscellaneous Small Exercise Equipment', 'Miscellaneous / Unknown', 38.0, 268, true),
  ('miscellaneous-unknown-miscellaneous-small-kitchen-appliances', 'Miscellaneous Small Kitchen Appliances', 'Miscellaneous / Unknown', 29.0, 269, true),
  ('miscellaneous-unknown-miscellaneous-sports-equipment', 'Miscellaneous Sports Equipment', 'Miscellaneous / Unknown', 29.0, 270, true),
  ('miscellaneous-unknown-miscellaneous-toys', 'Miscellaneous Toys', 'Miscellaneous / Unknown', 29.0, 271, true),
  ('miscellaneous-unknown-miscellaneous-yard-equipment', 'Miscellaneous Yard Equipment', 'Miscellaneous / Unknown', 38.0, 272, true),
  ('miscellaneous-unknown-motorcycle', 'Motorcycle', 'Miscellaneous / Unknown', 570.0, 273, true),
  ('miscellaneous-unknown-moving-fee-within-15-miles', 'Moving fee (within 15 miles)', 'Miscellaneous / Unknown', 124.0, 274, true),
  ('miscellaneous-unknown-musical-instruments', 'Musical Instruments', 'Miscellaneous / Unknown', 29.0, 275, true),
  ('miscellaneous-unknown-ophthalmic-chair', 'Ophthalmic Chair', 'Miscellaneous / Unknown', 171.0, 276, true),
  ('miscellaneous-unknown-ophthalmic-instrument-stand', 'Ophthalmic Instrument Stand', 'Miscellaneous / Unknown', 171.0, 277, true),
  ('miscellaneous-unknown-organ-electric', 'Organ - Electric', 'Miscellaneous / Unknown', 570.0, 278, true),
  ('miscellaneous-unknown-ottoman', 'Ottoman', 'Miscellaneous / Unknown', 48.0, 279, true),
  ('miscellaneous-unknown-outdoor-chair', 'Outdoor Chair', 'Miscellaneous / Unknown', 57.0, 280, true),
  ('miscellaneous-unknown-outdoor-fire-pit', 'Outdoor Fire Pit', 'Miscellaneous / Unknown', 57.0, 281, true),
  ('miscellaneous-unknown-outdoor-furniture', 'Outdoor Furniture', 'Miscellaneous / Unknown', 57.0, 282, true),
  ('miscellaneous-unknown-outdoor-furniture-sectional', 'Outdoor Furniture - Sectional', 'Miscellaneous / Unknown', 333.0, 283, true),
  ('miscellaneous-unknown-outdoor-lounge-chair', 'Outdoor Lounge Chair', 'Miscellaneous / Unknown', 57.0, 284, true),
  ('miscellaneous-unknown-oversized-wood-pallet', 'Oversized Wood Pallet', 'Miscellaneous / Unknown', 48.0, 285, true),
  ('miscellaneous-unknown-paint-1-gallon-paint-can', 'Paint - 1 Gallon Paint Can', 'Miscellaneous / Unknown', 23.0, 286, true),
  ('miscellaneous-unknown-paint-5-gallon-bucket', 'Paint - 5 Gallon Bucket', 'Miscellaneous / Unknown', 48.0, 287, true),
  ('miscellaneous-unknown-paper-shredder', 'Paper Shredder', 'Miscellaneous / Unknown', 38.0, 288, true),
  ('miscellaneous-unknown-peloton-exercise-bike', 'Peloton Exercise Bike', 'Miscellaneous / Unknown', 162.0, 289, true),
  ('miscellaneous-unknown-piano-baby-grand', 'Piano - Baby Grand', 'Miscellaneous / Unknown', 855.0, 290, true),
  ('miscellaneous-unknown-piano-grand', 'Piano - Grand', 'Miscellaneous / Unknown', 950.0, 291, true),
  ('miscellaneous-unknown-piano-upright', 'Piano - Upright', 'Miscellaneous / Unknown', 713.0, 292, true),
  ('miscellaneous-unknown-pilates-machine', 'Pilates Machine', 'Miscellaneous / Unknown', 95.0, 293, true),
  ('miscellaneous-unknown-pilates-reformer', 'Pilates Reformer', 'Miscellaneous / Unknown', 285.0, 294, true),
  ('miscellaneous-unknown-pillow', 'Pillow', 'Miscellaneous / Unknown', 19.0, 294, true),
  ('miscellaneous-unknown-pizza-oven-portable', 'Pizza Oven - Portable', 'Miscellaneous / Unknown', 76.0, 296, true),
  ('miscellaneous-unknown-pizza-oven-stand', 'Pizza Oven Stand', 'Miscellaneous / Unknown', 48.0, 297, true),
  ('miscellaneous-unknown-play-pen', 'Play Pen', 'Miscellaneous / Unknown', 38.0, 298, true),
  ('miscellaneous-unknown-playground', 'Playground', 'Miscellaneous / Unknown', 950.0, 299, true),
  ('miscellaneous-unknown-playset-indoor', 'Playset - Indoor', 'Miscellaneous / Unknown', 76.0, 300, true),
  ('miscellaneous-unknown-pool-table-or-commercial-game-room-table-games', 'Pool Table or Commercial Game Room Table Games', 'Miscellaneous / Unknown', 665.0, 301, true),
  ('miscellaneous-unknown-power-ride-on-toy', 'Power Ride On Toy', 'Miscellaneous / Unknown', 190.0, 302, true),
  ('printer', 'Printer - Free Standing', 'Miscellaneous / Unknown', 380.0, 303, true),
  ('miscellaneous-unknown-proof-of-recycling-appliances-only', 'Proof of Recycling - Appliances Only', 'Miscellaneous / Unknown', 48.0, 304, true),
  ('miscellaneous-unknown-recliner', 'Recliner', 'Miscellaneous / Unknown', 105.0, 305, true),
  ('miscellaneous-unknown-recumbent-exercise-cycle', 'Recumbent Exercise Cycle', 'Miscellaneous / Unknown', 190.0, 306, true),
  ('miscellaneous-unknown-rowing-exercise-machine', 'Rowing Exercise Machine', 'Miscellaneous / Unknown', 190.0, 307, true),
  ('miscellaneous-unknown-safe-large', 'Safe - Large', 'Miscellaneous / Unknown', 1140.0, 308, true),
  ('miscellaneous-unknown-safe-personal', 'Safe - Personal', 'Miscellaneous / Unknown', 67.0, 309, true),
  ('miscellaneous-unknown-safe-small', 'Safe - Small', 'Miscellaneous / Unknown', 200.0, 310, true),
  ('miscellaneous-unknown-sandbox-plastic', 'Sandbox - Plastic', 'Miscellaneous / Unknown', 48.0, 311, true),
  ('miscellaneous-unknown-sandbox-wooden', 'Sandbox - Wooden', 'Miscellaneous / Unknown', 86.0, 312, true),
  ('miscellaneous-unknown-satellite-dish-small', 'Satellite Dish - Small', 'Miscellaneous / Unknown', 95.0, 313, true),
  ('miscellaneous-unknown-scale', 'Scale', 'Miscellaneous / Unknown', 29.0, 314, true),
  ('miscellaneous-unknown-sewing-machine', 'Sewing Machine', 'Miscellaneous / Unknown', 29.0, 315, true),
  ('miscellaneous-unknown-shoes-and-clothing', 'Shoes and Clothing', 'Miscellaneous / Unknown', 29.0, 316, true),
  ('miscellaneous-unknown-shower-kit-stall-double', 'Shower Kit / Stall - Double', 'Miscellaneous / Unknown', 475.0, 317, true),
  ('miscellaneous-unknown-shower-kit-stall-single', 'Shower Kit / Stall - Single', 'Miscellaneous / Unknown', 285.0, 318, true),
  ('miscellaneous-unknown-slide', 'Slide', 'Miscellaneous / Unknown', 57.0, 319, true),
  ('miscellaneous-unknown-sliding-door', 'Sliding Door', 'Miscellaneous / Unknown', 171.0, 320, true),
  ('miscellaneous-unknown-snow-blower', 'Snow Blower', 'Miscellaneous / Unknown', 380.0, 321, true),
  ('miscellaneous-unknown-speakers', 'Speakers', 'Miscellaneous / Unknown', 48.0, 322, true),
  ('miscellaneous-unknown-stair-climbing-machine', 'Stair Climbing Machine', 'Miscellaneous / Unknown', 181.0, 323, true),
  ('miscellaneous-unknown-steamer', 'Steamer', 'Miscellaneous / Unknown', 29.0, 324, true),
  ('miscellaneous-unknown-stereo-system', 'Stereo System', 'Miscellaneous / Unknown', 48.0, 325, true),
  ('miscellaneous-unknown-stool', 'Stool', 'Miscellaneous / Unknown', 29.0, 326, true),
  ('miscellaneous-unknown-storage-shed', 'Storage Shed', 'Miscellaneous / Unknown', 2850.0, 327, true),
  ('miscellaneous-unknown-stroller', 'Stroller', 'Miscellaneous / Unknown', 38.0, 328, true),
  ('miscellaneous-unknown-swing-s', 'Swing(s)', 'Miscellaneous / Unknown', 95.0, 329, true),
  ('miscellaneous-unknown-swingset-medium', 'Swingset - Medium', 'Miscellaneous / Unknown', 190.0, 330, true),
  ('miscellaneous-unknown-table-saw', 'Table Saw', 'Miscellaneous / Unknown', 76.0, 331, true),
  ('miscellaneous-unknown-tanning-bed', 'Tanning Bed', 'Miscellaneous / Unknown', 475.0, 332, true),
  ('miscellaneous-unknown-tire-automotive', 'Tire - Automotive', 'Miscellaneous / Unknown', 38.0, 333, true),
  ('miscellaneous-unknown-toaster-oven', 'Toaster Oven', 'Miscellaneous / Unknown', 29.0, 334, true),
  ('miscellaneous-unknown-toilet', 'Toilet', 'Miscellaneous / Unknown', 67.0, 335, true),
  ('miscellaneous-unknown-tool-bench', 'Tool Bench', 'Miscellaneous / Unknown', 285.0, 336, true),
  ('miscellaneous-unknown-tool-box-small', 'Tool Box - Small', 'Miscellaneous / Unknown', 48.0, 337, true),
  ('miscellaneous-unknown-toolbox-freestanding', 'Toolbox - Freestanding', 'Miscellaneous / Unknown', 57.0, 338, true),
  ('miscellaneous-unknown-toolbox-large-rolling', 'Toolbox - Large Rolling', 'Miscellaneous / Unknown', 285.0, 339, true),
  ('miscellaneous-unknown-toy-box', 'Toy Box', 'Miscellaneous / Unknown', 48.0, 340, true),
  ('miscellaneous-unknown-trampoline', 'Trampoline', 'Miscellaneous / Unknown', 266.0, 341, true),
  ('miscellaneous-unknown-treadmill', 'Treadmill', 'Miscellaneous / Unknown', 181.0, 342, true),
  ('miscellaneous-unknown-trundle-bed', 'trundle bed', 'Miscellaneous / Unknown', 143.0, 343, true),
  ('miscellaneous-unknown-vacuum', 'Vacuum', 'Miscellaneous / Unknown', 38.0, 344, true),
  ('miscellaneous-unknown-vanity-large', 'Vanity - Large', 'Miscellaneous / Unknown', 143.0, 345, true),
  ('miscellaneous-unknown-vanity-medium', 'Vanity - Medium', 'Miscellaneous / Unknown', 76.0, 346, true),
  ('miscellaneous-unknown-vanity-small', 'Vanity - Small', 'Miscellaneous / Unknown', 67.0, 347, true),
  ('miscellaneous-unknown-water-heater', 'Water Heater', 'Miscellaneous / Unknown', 162.0, 348, true),
  ('miscellaneous-unknown-weed-eater-trimmer', 'Weed Eater / Trimmer', 'Miscellaneous / Unknown', 38.0, 349, true),
  ('miscellaneous-unknown-weight-bench', 'Weight Bench', 'Miscellaneous / Unknown', 38.0, 350, true),
  ('miscellaneous-unknown-weight-bench-set', 'Weight Bench Set', 'Miscellaneous / Unknown', 95.0, 351, true),
  ('miscellaneous-unknown-weight-machine', 'Weight Machine', 'Miscellaneous / Unknown', 190.0, 352, true),
  ('miscellaneous-unknown-wheelbarrow', 'Wheelbarrow', 'Miscellaneous / Unknown', 57.0, 353, true),
  ('miscellaneous-unknown-wheelchair-motorized', 'Wheelchair - Motorized', 'Miscellaneous / Unknown', 475.0, 354, true),
  ('miscellaneous-unknown-wheelchair-non-motorized', 'WheelChair - non motorized', 'Miscellaneous / Unknown', 38.0, 355, true),
  ('miscellaneous-unknown-wood-pallet', 'Wood Pallet', 'Miscellaneous / Unknown', 19.0, 356, true),
  ('dryer', 'Dryer', 'Washer / Dryer', 57.0, 357, true),
  ('washer-dryer-stackable-washer-and-dryer', 'Stackable Washer and Dryer', 'Washer / Dryer', 124.0, 358, true),
  ('washer-dryer-washer', 'Washer', 'Washer / Dryer', 57.0, 359, true);